// Generates src/data/countries.ts from the `world-countries` package so that
// ISO alpha-2/alpha-3/numeric codes are guaranteed to match the world-atlas
// TopoJSON ids (which use ISO 3166-1 numeric). Run: npm run generate:countries
import { createRequire } from 'node:module'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const require = createRequire(import.meta.url)
const all = require('world-countries')

function mapRegion(c) {
  if (c.region === 'Americas') {
    if (c.subregion === 'Caribbean') return 'Caribbean'
    if (c.subregion === 'South America') return 'South America'
    return 'North America'
  }
  if (c.region === 'Asia') {
    return c.subregion === 'Western Asia' ? 'Middle East' : 'Asia'
  }
  return c.region // Africa | Europe | Oceania
}

const rows = all
  .filter((c) => c.ccn3 && c.region && c.region !== 'Antarctic')
  .map((c) => ({
    name: c.name.common,
    iso2: c.cca2,
    iso3: c.cca3,
    numeric: c.ccn3,
    region: mapRegion(c),
    independent: c.independent === true,
    aliases: (c.altSpellings || [])
      .filter((a) => a.length > 2 && a.toLowerCase() !== c.name.common.toLowerCase())
      .slice(0, 4),
  }))
  .sort((a, b) => a.name.localeCompare(b.name))

const body = rows.map((r) => `  ${JSON.stringify(r)},`).join('\n')

const out = `// AUTO-GENERATED by scripts/generateCountries.mjs — do not edit by hand.
import type { Country } from '../types'

export const countries: Country[] = [
${body}
]

export const countriesByIso2: Map<string, Country> = new Map(
  countries.map((c) => [c.iso2, c]),
)

export const countriesByNumeric: Map<string, Country> = new Map(
  countries.map((c) => [c.numeric, c]),
)

/** Sovereign states only — the denominator for "% of countries visited". */
export const independentCountryCount = countries.filter((c) => c.independent).length
`

const dest = join(dirname(fileURLToPath(import.meta.url)), '../src/data/countries.ts')
writeFileSync(dest, out)
console.log(`Wrote ${rows.length} countries to ${dest}`)
